name: "Release module"

on:
  workflow_dispatch: {}

permissions:
  contents: read # needed for checkout
  packages: write # needed for GHCR access

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CUE
        uses: cue-lang/setup-cue@main

      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main

      - name: Lint
        run: |
          timoni mod lint .

      - name: Test instance build
        run: |
          timoni build -n testing test .

      - name: Push
        run: |
          timoni mod push . \
            oci://ghcr.io/${{ github.repository_owner }}/modules/app-template \
            --version ${{ github.ref_name }} \
            --creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
